title: 希望と夢
author: Erick Garcia
email: me@erick-garcia.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hello! this is my space to write about whatever I want about feel
  free to ask any questions about any related topic.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    # github:  jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
kramdown:
    input: GFM
    syntax_highlighter: pygments

highlighter: rouge
markdown: kramdown
