#+TITLE: 日本語の試験
#+LAYOUT: post
#+TAGS: japanese class test

* 復習(ふくしゅう)
Pg. 53 (PDF pg. 63)
1.	Vないで。Casual Conversation – Prohibition 「禁止(きんし)」
a.	あした持ってくるのを忘れないでね。

2.	V「辞書(じしょ)」な。Jisho Verb + な – Strong Prohibition
例：走るな…　吸うな…

3.	V「Causative」ていただけないでしょうか。Very polite form of asking permission to do something. Do not confuse with Vていただけないでしょうか, in which you are asking someone to do something. 

4.	～ば～ほど＝“The more/less ～, the more/less ～”　How to conjugate ～ば：
a.	～い→ければ
b.	～な→であれば
c.	名詞→であれば
d.	動詞
i.	う→えば
ii.	む→めば
iii.	る→れば
e.	する→すれば
f.	くる→くれば
例：食べれば食べるほど太ります。←Note that verbs must be “repeated,” VばVほど
例：日本語は勉強しなければしないほど分からなくなります。
例：いいレストランであればあるほど高い。


5.	N以外(いがい)の／以外に＝ “other than～; besides～”
a.	学期の始めは、教科書以外にいろいろ買うものがある。
At the beginning of the semester, there are many other things to buy besides textbooks.
b.	文部科学省以外の奨学金もあります。
There are many other scholarships than that from the Ministry of MEXT.

6.	必(かなら)ずしも～というわけではない＝”it does not necessarily mean that…”

7.	Nばかり＝”Nothing but～”

8.	なるべく＝”as ～ as possible”
a.	宿題は、なるべき次の日に出してください。
Please hand in homework the next day if possible.

9.	V (plain) べき＝”should; ought to”
a.	悪い友達の意見(いけん)は聞くべきではない。
One should not listen to the opinions of bad friends.

Pg. 71 (PDF pg. 81)
1.　別(べつ)に（～ない）＝”Not particularly”
a.	先生：日本語のクラスは、どう。難(むずか)しい？
学生：ううん、別に。

2.	～かな (To wonder)
a.	日本の人口はどうぐらいかな。
What is the population of Japan, I wonder.

3.	 たしか＝ “If I remember correctly” / たしかに＝ “Certainly”
a.	日本の人口は、たしか一億に千万ぐらいでしょう。
If I’m not mistaken, Japan’s population is about 120,000,000.

4.	 XはYで有名(ゆうめい)だ＝ “X is famous for Y”
a.	ミルウォーキーは、ビールで有名です。

5.	 Nにする＝ “To decide on N; to have/take N”
a.	私は、すきやきにします。
I will have sukiyaki.

6.	 ～ようだ＝ “It seems that; it looks like ～” / Nのように＝ “like; as if it were”
a.	日本人は仕事(しごと)が好きのようです。
Japanese seem to like work.
b.	「X のようなY」＝ X looks/behaves like Y.
例：田中さんは、女のような人です。
Mr. Tanaka looks like a woman. 
c.	赤ちゃんは、ペンギンのように歩きます。
Babies walk like penguins. 

7.	 さえ＝ “Even”
a.	時々夏は暑くて、眠れないことさえあります。

8.	 いつのまにか＝ “before one knows it; before one realizes”
a.	お金はいつのまにかなくなってしまいます。
Money Is gone before you know it.

9.	 になれる＝ “Be used to; be accustomed to” (Follows a noun or a sentence followed by の).
a.	日本の生活になれてきました。
I have become used to the Japanese way of life. 
b.	タトゥーの痛みになれた。
I got used to tattoo pain.

10.	 V ないで済(す)む
a.	勉強しないで済んで、卒業します。

11.	 ～ずつ＝ “each; at a time”
a.	私は毎日漢字を五つずつ覚えることにしています。
I memorize five kanji every day. 
b.	一人一枚ずつ取ってください。
Please take one sheet each.

12.	 以(い)上(うえ)＝ “more than”
a.	一奥さんがあるは悪いです。
